name: Copy Files to GCS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Prepare variables for Terraform
        run: |
          echo "GCS_KEY_BASE64=${{ secrets.GCS_KEY }}" >> $GITHUB_ENV
        shell: bash
        env:
          GCS_KEY_BASE64: ${{ env.GCS_KEY_BASE64 }}
         
      - name: Apply Terraform
        run: |
          terraform init
          terraform apply -auto-approve
          
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{secrets.GCP_EMAIL}}
          service_account_key: ${{secrets.GCP_KEY}}
          project_id: dev-project-403711 
        

      - name: Clean up
        run: |
          terraform destroy -auto-approve
